apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagepolicies.securityenforcement.admission.cloud.ibm.com
  labels:
    app: portieris
spec:
  group: securityenforcement.admission.cloud.ibm.com
  names:
    kind: ImagePolicy
    listKind: ImagePolicyList
    plural: imagepolicies
    singular: imagepolicy
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterimagepolicies.securityenforcement.admission.cloud.ibm.com
  labels:
    app: portieris
spec:
  group: securityenforcement.admission.cloud.ibm.com
  names:
    kind: ClusterImagePolicy
    listKind: ClusterImagePolicyList
    plural: clusterimagepolicies
    singular: clusterimagepolicy
  scope: Cluster
  version: v1beta1
---
apiVersion: v1
kind: Secret
metadata:
  name: portieris-certs
  namespace: ibm-system
type: Opaque
data:
  serverCert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lKQU9FOCt3TWxoYnZWTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmN4RlRBVEJnTlYKQkFNTURIQnZjblJwWlhKcGMxOWpZVEFnRncweE9ERXhNalV3TURJek1EWmFHQTh5TWpreU1Ea3dPVEF3TWpNdwpObG93SXpFaE1COEdBMVVFQXd3WWNHOXlkR2xsY21sekxtbGliUzF6ZVhOMFpXMHVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcHpRR1A1bTN1ZHM3UDJKOUdCMWJrZ244eHFaQWdHVHEKSy8vUTNpbjJobjRaVXRZcituSitKT0c1a0JKNXhxUG5PaXRNaU5HT2JLUjR5bURWVUJ5NDcxalpaZm5JVzJMSQoyVklaN2hZdUx0ZXViUXZXQ0IyOG03WjJhZ2pWVnFwMm5BN3l6a1cwS21OR3dleVBXZVFmVThRY0NVS1F0K05JCk8xbVZaOGNkMGZvL3gyMnU1TUhOVnh6TmdVWDNGbjFqeVV2bER4MlBCODlub25YZWJkbCthOXozTEFUUGw0LzgKS01pRTFOdUl5Wi9qTDJ2bVA4S3ZDWU9YV3RQRjU0ekg4enlrM2VXWXFpeVdjU1NvTk1IMzUvSWtmTDRnclZJZAprWU5iN1FXbmNvRko4dktUTGZCQnRRNUtnclRjMkVLK3pmTmtSek1hd2FuS0VXWHRIS01BWndJREFRQUJvemt3Ck56QUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUVBd0lGNERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFnWUkKS3dZQkJRVUhBd0V3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUdGaXg5WTFqSUFVdUZtcUt2R1FOQ1R3UkhSbQpVOGdVbjBoZk0rYXE0MisxSE1ndzZsZVNSNFUrM1lXaFRoMDZzUFZ1UDQvU01CZE5pRDVZNlBsQlRiMWZCbWRCCk1qcm9CaVJBRjBkb1JZa01CbVdtSnRIaThZcWlhRkh1RDNVSTl5VmtWY1U0VUtmd0hNei9xQnFGV0loNGZMbjQKOVJOU0ZmaGpFMmRLbmI3YkV4NlZ0QWhiSmg0RDB5NDhLRSt2aDBQWnhmL2NlcFFCb0k5RHdyM0JvVXpyMWQ3bQpLN2MyczBPUzNNS085SEVjYVFDNmRmc1dzWFUwOTRRdDZ3Y2V1K2VabUp6RHNjWEFORVhGVGdDYjZnQWlYYUlaCnl0cTNZbFlwWHRwdzFSMkpIRDZNV2V4R2RLcWVSRVJ0MXNmektVUFNoUHJmZGs2L1hyNkhRbEtjeHRrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  serverKey.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcHpRR1A1bTN1ZHM3UDJKOUdCMWJrZ244eHFaQWdHVHFLLy9RM2luMmhuNFpVdFlyCituSitKT0c1a0JKNXhxUG5PaXRNaU5HT2JLUjR5bURWVUJ5NDcxalpaZm5JVzJMSTJWSVo3aFl1THRldWJRdlcKQ0IyOG03WjJhZ2pWVnFwMm5BN3l6a1cwS21OR3dleVBXZVFmVThRY0NVS1F0K05JTzFtVlo4Y2QwZm8veDIydQo1TUhOVnh6TmdVWDNGbjFqeVV2bER4MlBCODlub25YZWJkbCthOXozTEFUUGw0LzhLTWlFMU51SXlaL2pMMnZtClA4S3ZDWU9YV3RQRjU0ekg4enlrM2VXWXFpeVdjU1NvTk1IMzUvSWtmTDRnclZJZGtZTmI3UVduY29GSjh2S1QKTGZCQnRRNUtnclRjMkVLK3pmTmtSek1hd2FuS0VXWHRIS01BWndJREFRQUJBb0lCQUZyUXV3UVliZDRZNFZsUQpHVG5iMkR5K0IvbXRteU1ockw4eE56VXovWjZYSnhJREdlZngvK253WUdXTVkzQXMzZzZPTGdleUtuVi83OHVjClJNQTZtWWdHN2kyaE9kM0pEZVpiM1pHZm9uMzJ6OXFTcnpIQlZRd09Vc3JNK1hNVkswOGdIMmxDR3RWYkRyZU4KMFY2MXRQNCthaXZ0WjhVNVFhWmF4ZmVVQXZKazVRM3BkQ1g0QlcxT1RXaUo0VEluREJuNnFEaHRGNlhsTVR3SQpjemhSYlpEQ1dVSmY3eHZrM0s4Ump5TmF0UWVkcmc2MWtjZVFMa3U5NCtHaDBJNmNGQ3FHb05rbGplOG9ObTZrCmFjd2FaWXVMenhNcmdWT3hkZk9PZlZvMEhMK0c0ZFhTZjhoVUx4MU1uaVltSWZSZzhydXZxU0hxNFJPRTZXUEYKL3dLeVhjRUNnWUVBMXZudkE1bnp1MWs5WUlaaWhicFFBbkphYjVpNXl1ZGZUTkxMMWNzZ3o2a3Bpam9RWmsxWgp3RUtwYVhIWFJXUGwxWUZ4VFRsN1BRaHROeDl6aDkydlc5QlYyMWN0cmFyVDlabzlyTlNMUXhxaUVxQXpsN1IyCnNRQ2NMdTljNWV4cWpUcWc2U3RZaTZoOVJKNzhHVzBCU29WMW9XVnhYajBudFVvSnZZbE1RSDhDZ1lFQXh4eEYKTkw4VXdYM0dKZ1Q5cW9VNTlzNllZU2pMZ0JseEFMWGdhTVUxYnN1UDAzQVAyRGUrVSt1SzJuUFZEYXdTY1hoeQpGL0FISXhpZUlhTkZhbDJvME54UXRudmllS3ZSd1graGNzR2VTUTM0ekwyMmZPVkdlK3Vod1BiNWcyT1plWU82CjRoMWdET3BrbE44c3FuMEtzQTZZSW96c0NCSnVlKzdyWmVsMVRCa0NnWUFhYk82c2lxZ2pSM3o3K0lqejEwc3UKZ2RBTUY4SCs1eUlYMTNHbS9pa3lYYUQxbE4yZk5iTHFwMGNiNXhxSE5SaHpmazNuS0VHMTV1dEY4MS9JTzcvcQprVmw4ZE9Md2ppY3Y4WjNUT08xRmVtaWgwWCtHRG5Eb29TS1J3bXF3K0xiQVZZeWlIT250Z1BDbEZzWDJlaWZHCmVWRlVYWnZwOGFxSDVtbjhHbng5RVFLQmdHTllGS09qcnp4M2Y3VWFpbUpaUkxtRERQNTFOMHY3NWFrQUZpN1EKTHIvUUt6dkl6dThIcVJ3QUN2RENHSXhRelliMkhKOGE4TVN2Rkw4ZDBwV21rNE5hV1o4aklyVW9yV2lKUU1tYwpGMWpGOHR4Y3o3OXpPZjY4YTZGMjJMbVlxVXU2MFRUZWlUMEllaFRaWVZUVFBORHBCems5N01wK1A4ZndSbDA3CjVYMkpBb0dCQU1PMEVQYXR5UitQVnBCOUNYQ3FWcDRZcklGZ3NwTGl3Uldoc1BaOXcyVmpDbkw5VSs3REFZSDAKZVllTWpZY0NYek9DK2VuaGpUSWp1dlRQVzk5T0dOaTNQcXI5T1B5VVl2T0FNeEEvRkpKcEkvekI5bDJOVEYrUQp4RXpNeHZPUVk0bWwwOHl5Nnc1MmlSWmVFOWcxK2t0b3BiaG9pMXl3QzJoWDcweFM5a1dUCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  ca.pem: <sed-me>
---
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: portieris-default-image-policy
  namespace: ibm-system
spec:
  repositories:  
  # This policy prevents Portieris from blocking itself
  - name: "docker.io/ibmcom/portieris:0.5.1"
    policy:
  # This policy allows Portieris to use Hyperkube to configure your cluster. This policy must exist if you uninstall Portieris.
  - name: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
    policy:    
---
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: portieris-default-cluster-image-policy
spec:
    repositories:
    # This enforces that all images deployed to this cluster pass trust
    # IMPORTANT: Review this policy and replace it with one that meets your requirements.
    - name: "*"
      policy:
        trust:
          enabled: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portieris
  namespace: ibm-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portieris
  labels:
    app: portieris
rules:
- apiGroups: ["securityenforcement.admission.cloud.ibm.com"]
  resources: ["imagepolicies", "clusterimagepolicies"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admission-portieris-webhook
  labels:
    app: portieris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portieris
subjects:
  - kind: ServiceAccount
    name: portieris
    namespace: ibm-system

---
apiVersion: v1
kind: Service
metadata:
  name: portieris
  namespace: ibm-system
  labels:
    app: portieris
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: portieris
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portieris
  namespace: ibm-system
  labels:
    app: portieris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portieris
  template:
    metadata:
      labels:
        app: portieris
    spec:
      serviceAccountName: portieris
      containers:
        - name: portieris
          image: "docker.io/ibmcom/portieris:0.5.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: portieris-certs
            readOnly: true
            mountPath: "/etc/certs"                    
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
